### ISSUE TITLE
incubation moisture contents

### ISSUE THREAD

**Issue by kaizadp** [bpbond/3soils#11]
@bpbond I am trying to figure out the moisture contents of the soils during the incubations. (moisture content of drought vs. saturated, etc.). You may have addressed these issues, but I can't find it in the code:

1. CPCRW drought cores have negative moisture, and I don't know why the final weights > initial.
2. SR drought cores in `valve_key` have a potpietin... weight of only 6 g, whereas all the others are 50+ g.  Was this fixed somewhere in the code?

**Comment by bpbond** [comment]
Should I check this as part of https://github.com/kaizadp/tes_3soils_2019/issues/24 ?

**Comment by kaizadp** [comment]
Yes, please. That would be great.

**Comment by bpbond** [comment]
The. mass data jumps around a _lot_.

![mass](https://user-images.githubusercontent.com/1956468/67754011-11ff3400-fa0c-11e9-93ed-db5054fc7c27.png)

As you note, the CPCRW drought cores in particular seem problematic:
![cpcrw_drought](https://user-images.githubusercontent.com/1956468/67753947-ee3bee00-fa0b-11e9-97ba-b7ef8b5487e7.png)

Focusing on the. data for C23:

<img width="848" alt="Screen Shot 2019-10-29 at 5 25 36 AM" src="https://user-images.githubusercontent.com/1956468/67754277-918d0300-fa0c-11e9-8e44-616733bbc802.png">

**Comment by bpbond** [comment]
>SR drought cores in valve_key have a potpietin... weight of only 6 g, whereas all the others are 50+ g. Was this fixed somewhere in the code?

No. Wow, I see what you mean! Those five cores have "6.45" entered for their `mCap+Linear g` columns.

**Comment by kaizadp** [comment]
> As you note, the CPCRW drought cores in particular seem problematic:
I have no idea why (a) these values are jumping around so much, or (b) why C24, C25 are missing weights.

My solution is to use the final pre_incubation weights/moistures as the values for the incubation.
This shouldn't change Picarro results if you're only using dry weight, which we assume remains constant throughout. 

edit: I don't know how much I trust the total weights. A little variability is fine, but this is too much. And even the drought_pre_incubation weights for CPCRW were giving me negative moisture.

**Comment by kaizadp** [comment]
>No. Wow, I see what you mean! Those five cores have "6.45" entered for their mCap+Linear g columns.

I'm going to assume that's 56.45 g, making it somewhat consistent with the other cores.

**Comment by kaizadp** [comment]
@bpbond If you're using dry soil weights from the same master file, the SR_drought dry weights for respiration are probably wrong, 50 g higher than they should be. (related to the 56.45 vs. 6.45 g problem above).  

I have calculated the dry weights for *all cores* again.
Code is in my 3Soils repo: https://github.com/kaizadp/tes_3soils_2019/blob/01658844bbac4f704ec59bee7bde31296258f4ed/1b-moisture.R#L11

Output file with corrected dry weights is on GDrive: https://drive.google.com/file/d/1lmdAVp5JrAktg1Ylw52fWDrHpDIp0zJ8/

**Comment by bpbond** [comment]
I think this is largely obviated by shifting to new repository, so closing.
